name: SSE CI/CD

on: [push]
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v6
        - name: "Install style checker clang"
          run: sudo apt-get install -y clang-format
        - name: "Run style check"
          run: clang-format --dry-run -Werror $(find src tests -name "*.cpp" -o -name "*.hpp")
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: "Install eigen"
        run: sudo apt-get install -y libeigen3-dev
      - name: "Install yaml"
        run: sudo apt-get install -y libyaml-cpp-dev
      - name: "Install boost"
        run: sudo apt-get install -y libboost-test-dev
      - name: "Start build process with creating build folder"
        run: mkdir build
      - name: "Run cmake"
        working-directory: build
        run: cmake ..
      - name: "Run make"
        working-directory: build
        run: make -j
      - name: "Upload build Artifact for Tests"
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
          retention-days: 1
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: "Download build Artifact"
        uses: actions/download-artifact@v4
        with:
          name: build
      - name: "Install eigen"
        run: sudo apt-get install -y libeigen3-dev
      - name: "Install yaml"
        run: sudo apt-get install -y libyaml-cpp-dev
      - name: "Install boost"
        run: sudo apt-get install -y libboost-test-dev
      - name: "Run Tests"
        working-directory: build-data
        run: make test